platform :ios, '16.0'

target 'pstuian' do
  use_frameworks!

  # The shared Kotlin module
  pod 'presentation', :path => '../../presentation'

  # Firebase pods
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseMessaging'
end

# Ensure the Pods project also disables sandboxing for the Gradle script to run
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
