[versions]
# App Config
gradle = "8.9.1"
compileSdk = "36"
minSdk = "24"
targetSdk = "34"
versionCode = "7"
versionName = "3.0.0"
versionCodeDb = "2"
proguardRules = "proguard-rules.pro"
dimension = "environment"

# Kotlin
kotlin = "2.3.20"
kotlinx-serialization = "1.11.0"
kotlinx-datetime = "0.7.1"
coroutines = "1.10.2"

# Compose
composeActivity = "1.13.0"
compose-multiplatform = "1.10.3"
compose-material3 = "1.9.0"
compose-material-icons = "1.7.3"
compose-navigation-version = "2.9.2"

# Androidx
androidx-lifecycle = "2.8.2"
androidx-core = "1.15.0"

# Libraries
coreKtx = "1.15.0"
workManager = "2.11.2"
ktor = "3.4.2"
documentFile = "1.0.1"

coil-version = "3.4.0"
firebase-bom = "33.1.1"
firebase-kmm = "2.4.0"
google-services-version = "4.4.4"
koin = "4.2.1"
napier = "2.7.1"
compottie = "2.1.0"

# Test
junit = "4.12"
extJunit = "1.1.1"
espresso = "3.2.0"
runner = "1.5.2"
kotlinTest = "2.1.10"
core = "1.7.0"
firebaseMessagingKtx = "25.0.1"

[libraries]
# Build Logic
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services-version" }

# Std Lib
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
jetbrains-kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }

# Compose
# androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
# androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
# androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
# androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
# androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
# androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "compose-multiplatform" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation-version" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Work Manager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "workManager" }

# Utilities
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentFile" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-kmm-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebase-kmm" }
firebase-kmm-firestore = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "firebase-kmm" }
firebase-kmm-database = { group = "dev.gitlive", name = "firebase-database", version.ref = "firebase-kmm" }

# Koin
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }

# Image Loader
# coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-version" }

# Animation
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }

# Logging
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradle" }
android-lint = { id = "com.android.lint", version.ref = "gradle" }
